# Exploratory Data Analysis and Data Cleaning

### Importing Libraries

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
MergedDataset = pd.read_csv(r"C:\Users\Rishik Reddy\OneDrive\Desktop\Travelnfo\DataSets\ProcessedData\Merged_Tourism_Dataset.csv")
MergedDataset.head()

,Country Name,Country Code,Year,Arrivals,Expenditure,TourismGrowth,AvgSpendingPerTourist
0,Aruba,ABW,2006,1285000.0,2.410000e+08,-0.077760,187.548638
1,Angola,AGO,2006,121000.0,3.930000e+08,-42.380952,3247.933884
2,Albania,ALB,2006,937000.0,9.890000e+08,25.267380,1055.496265
3,Andorra,AND,2006,10737000.0,NaN,-2.823785,NaN
4,Argentina,ARG,2006,4173000.0,4.047000e+09,9.155114,969.805895

In [32]:
MergedDataset.dtypes

Country Name     object
Country Code     object
Year              int64
Arrivals        float64
Expenditure     float64
dtype: object

In [33]:
MergedDataset.shape
print("Number of rows:", MergedDataset.shape[0])
print("Number of columns:", MergedDataset.shape[1])

Number of rows: 4408
Number of columns: 5

In [34]:
MergedDataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4408 entries, 0 to 4407
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  4408 non-null   object
 1   Country Code  4408 non-null   object
 2   Year          4408 non-null   int64
 3   Arrivals      3133 non-null   float64
 4   Expenditure   2800 non-null   float64
dtypes: float64(2), int64(1), object(2)
memory usage: 172.3+ KB

In [35]:
MergedDataset.describe()

              Year      Arrivals   Expenditure
count  4408.000000  3.133000e+03  2.800000e+03
mean   2014.000000  2.806580e+07  1.533736e+10
std       5.477847  1.145607e+08  6.903457e+10
min    2005.000000  1.100000e+03  3.100000e+05
25%    2009.000000  5.260000e+05  1.947500e+08
50%    2014.000000  1.916000e+06  7.795000e+08
75%    2019.000000  8.084000e+06  5.240000e+09
max    2023.000000  1.275198e+09  8.878223e+11

### cheacking NULL values

In [36]:
MergedDataset.isnull().sum()

Country Name       0
Country Code       0
Year               0
Arrivals        1275
Expenditure     1608
dtype: int64

In [37]:
MergedDataset['Growth_%'] = MergedDataset.groupby('Country Name')['Arrivals'].pct_change()*100
MergedDataset.head()

  Country Name Country Code  Year    Arrivals  Expenditure  Growth_%
0        Aruba          ABW  2005   1286000.0  250000000.0       NaN
1  Afghanistan          AFG  2005         NaN          NaN       NaN
2       Angola          AGO  2005    210000.0  135000000.0       NaN
3      Albania          ALB  2005    748000.0  808000000.0       NaN
4      Andorra          AND  2005  11049000.0          NaN       NaN

In [ ]:
MergedDataset.rename(columns={'Growth_%': 'TourismGrowth'}, inplace=True)
MergedDataset.head(500)

# NOTE : The first year for each country will show NAN beacause there is no previous year to compare to calculate the growth percentage

,Country Name,Country Code,Year,Arrivals,Expenditure,TourismGrowth
0,Aruba,ABW,2005,1286000.0,2.500000e+08,NaN
1,Afghanistan,AFG,2005,NaN,NaN,NaN
2,Angola,AGO,2005,210000.0,1.350000e+08,NaN
3,Albania,ALB,2005,748000.0,8.080000e+08,NaN
4,Andorra,AND,2005,11049000.0,NaN,NaN
...,...,...,...,...,...,...
495,Switzerland,CHE,2007,8448000.0,1.298400e+10,7.439908
496,Channel Islands,CHI,2007,NaN,NaN,NaN
497,Chile,CHL,2007,NaN,1.408000e+09,NaN
498,China,CHN,2007,131873000.0,NaN,5.547374
499,Cote d'Ivoire,CIV,2007,182000.0,6.060000e+08,NaN

In [4]:

MergedDataset['TourismGrowth'] = (
    MergedDataset['TourismGrowth']
    .astype(str)
    .str.replace('%', '', regex=False)
)
MergedDataset['TourismGrowth'] = pd.to_numeric(MergedDataset['TourismGrowth'], errors='coerce')
MergedDataset['TourismGrowth'].dtypes

dtype('float64')

In [5]:
avg_growth = MergedDataset['TourismGrowth'].mean()
print("Average Tourism Growth:", avg_growth)

Average Tourism Growth: 3.086977000365155

### Spending Per Tourist

In [39]:
MergedDataset['AvgSpendingPerTourist'] = MergedDataset['Expenditure']/MergedDataset['Arrivals']
MergedDataset.head()

,Country Name,Country Code,Year,Arrivals,Expenditure,TourismGrowth,AvgSpendingPerTourist
0,Aruba,ABW,2005,1286000.0,250000000.0,NaN,194.401244
1,Afghanistan,AFG,2005,NaN,NaN,NaN,NaN
2,Angola,AGO,2005,210000.0,135000000.0,NaN,642.857143
3,Albania,ALB,2005,748000.0,808000000.0,NaN,1080.213904
4,Andorra,AND,2005,11049000.0,NaN,NaN,NaN

###  Top 10 Countries by Tourism Revenue

In [40]:
remove_words = "income|dividend|IBRD|IDA|Euro|OECD|area|total"

merged = MergedDataset[~MergedDataset['Country Name'].str.contains(remove_words, case=False, na=False)]
merged.groupby('Country Name')['Expenditure'] \
      .sum() \
      .sort_values(ascending=False) \
      .head(10)

Country Name
United States                               2.078767e+12
Germany                                     1.431008e+12
France                                      7.832380e+11
Russian Federation                          5.318220e+11
Japan                                       5.166310e+11
Australia                                   4.725790e+11
Fragile and conflict affected situations    4.410509e+11
Korea, Rep.                                 3.989090e+11
Belgium                                     2.976420e+11
Brazil                                      2.891010e+11
Name: Expenditure, dtype: float64

### COVID Impact (2019–2021)

In [41]:
MergedDataset[MergedDataset['Year'].isin([2019,2020,2021])]

,Country Name,Country Code,Year,Arrivals,Expenditure,TourismGrowth,AvgSpendingPerTourist
3248,Aruba,ABW,2019,1951000.0,3.990000e+08,2.846600,204.510507
3249,Afghanistan,AFG,2019,NaN,1.680000e+08,NaN,NaN
3250,Angola,AGO,2019,218000.0,7.170000e+08,0.000000,3288.990826
3251,Albania,ALB,2019,6406000.0,1.852000e+09,8.081660,289.103965
3252,Andorra,AND,2019,8235000.0,1.870000e+08,-1.116715,22.707954
...,...,...,...,...,...,...,...
3939,Samoa,WSM,2021,NaN,NaN,0.000000,NaN
3940,Kosovo,XKX,2021,NaN,NaN,NaN,NaN
3941,"Yemen, Rep.",YEM,2021,NaN,NaN,0.000000,NaN
3942,Zambia,ZMB,2021,NaN,NaN,0.000000,NaN
3943,Zimbabwe,ZWE,2021,NaN,NaN,0.000000,NaN

In [42]:
data_2019= MergedDataset[MergedDataset['Year'] == 2019]['Arrivals'].mean()
data_2020= MergedDataset[MergedDataset['Year'] == 2020]['Arrivals'].mean()
data_2021= MergedDataset[MergedDataset['Year'] == 2021]['Arrivals'].mean()
print("Average Arrivals in 2019:", data_2019.round(2))
print("Average Arrivals in 2020:", data_2020.round(2))  
print("Average Arrivals in 2021:", data_2021)

Average Arrivals in 2019: 38391354.55
Average Arrivals in 2020: 4727821.54
Average Arrivals in 2021: nan

In [43]:
drop_percent = ((data_2020 - data_2019) / data_2019) * 100
print("Total arrivals from 2019 to 2020:",drop_percent.round(2), "%")

Total arrivals from 2019 to 2020: -87.69 %

### Correlation Between Arrivals & Expenditure

In [44]:
MergedDataset[['Arrivals','Expenditure']].corr()

             Arrivals  Expenditure
Arrivals     1.000000     0.968205
Expenditure  0.968205     1.000000

In [6]:
MergedDataset.to_csv("DataSets/Merged_Tourism_Dataset.csv", index=False)
MergedDataset.head()

,Country Name,Country Code,Year,Arrivals,Expenditure,TourismGrowth,AvgSpendingPerTourist
0,Aruba,ABW,2005,1286000.0,250000000.0,NaN,194.401244
1,Afghanistan,AFG,2005,NaN,NaN,NaN,NaN
2,Angola,AGO,2005,210000.0,135000000.0,NaN,642.857143
3,Albania,ALB,2005,748000.0,808000000.0,NaN,1080.213904
4,Andorra,AND,2005,11049000.0,NaN,NaN,NaN

In [7]:
MergedDataset.to_csv("DataSets/Processed/Merged_Tourism_Dataset.csv", index=False)